#### LIBRERIAS ####




#### SOURCE ####
source("Scripts/    nombredelscript.R     ")

#NO ERROR
#GRAFICOS Y CSV SE TIENE QUE ACTUALIZAR

#ENTREGAR TODO JUNTO, Y COMPRIMIR EN ZIP --> SUBIR ESTA CARPETA ZIP EN MOODEL
#EN MODEL QUE NO ESTEN LOS DATOS ORIGINALES DENTRO, CARPETA VACIA

#EN DRIVE --> SI TIENE QUE ESTAR LOS DATOS ORIGINALES CON LOS EXCELS
#EJECUTAR TODO CON UN RHISTORI Y QUE GUARDE EL .RDATA PARA TENER EL ENVIROMENT




